// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7Gpvimc1f-KTsHx6Yka6frH0NYsNxR6w',
    appId: '1:399398963854:android:6fac765add2e659ff497df',
    messagingSenderId: '399398963854',
    projectId: 'robust-arcadia-460300-s2',
    storageBucket: 'robust-arcadia-460300-s2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDW70gZoUxlEAGHqWcdzZvUhW0t4sD_DIA',
    appId: '1:399398963854:ios:f6498014f73cabe2f497df',
    messagingSenderId: '399398963854',
    projectId: 'robust-arcadia-460300-s2',
    storageBucket: 'robust-arcadia-460300-s2.firebasestorage.app',
    androidClientId: '399398963854-0n0hgqfs2ic1k2eagfina00n2urhdrg1.apps.googleusercontent.com',
    iosClientId: '399398963854-flg1i1cgglo8vd3juca70ce9o5r6nk7i.apps.googleusercontent.com',
    iosBundleId: 'com.example.project',
  );
}
